name: create-infra
on: [workflow_dispatch, push]
env:
    AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
    AWS_DEFAULT_REGION: 'us-east-1'
jobs:
    create-infra:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{steps.step1.outputs}}
        steps:
            - name : See output
              id : step1
              run: echo "Hello there" 
            - name: Clone repo
              uses: actions/checkout@v4
            - name: print env var
              run: echo $AWS_DEFAULT_REGION


    second-job:
        runs-on : ubuntu-latest
        needs : [create-infra]
        steps:
            - name: second print
              run: aws configure list
            - name: print env var
              run:  echo $AWS_DEFAULT_REGION
            - name: output from previous step
              run: ${{needs.create-infra.outputs.output1}}