name: create-infra
on: [workflow_dispatch, push]
env:
    AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
    AWS_DEFAULT_REGION: 'us-east-1'
jobs:
    create-key-pair:
        runs-on: ubuntu-latest
        steps:
            - name: print value
              run: aws configure list
            - name: print env var
              run: echo $AWS_DEFAULT_REGION

    second-job:
        runs-on : ubuntu-latest
        needs : [create-key-pair]
        steps:
            - name: second print
              run: aws configure list
            - name: print env var
              run:  echo $AWS_DEFAULT_REGION