name: create-infra
runs-on: [workflow-dispatch, push]
jobs:
    name: create key pair
    runs-on: ubuntu-latest
    steps:
        - name: print value
          run: echo "value"
    name: second job
    runs-on : ubuntu-latest
    needs : [create key pair]
    steps:
        - name: second print
          run: echo "second value"