name: create-infra
on: [workflow-dispatch, push]

jobs:
    create-key-pair:
        runs-on: ubuntu-latest
        steps:
            - name: print value
              run: echo "value"

    second-job:
        runs-on : ubuntu-latest
        needs : [create-key-pair]
        steps:
            - name: second print
              run: echo "second value"